apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: ngnex-app
spec:
  selector:
    matchLabels:
      app: ngnex-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ngnex-app
    spec:
      containers:
        - name: angular
          image: dannielaramirez/angular8demomaster:latest
          ports:
            - containerPort: 80
